### ISSUE TITLE
Today's date always highlighted

### ISSUE THREAD

**Issue by dcolley** [ParadeTo/vue-date-range#13]
When I enter a page/view, today's date is always highlighted
![image](https://user-images.githubusercontent.com/1845970/31347010-d95f16d0-ad12-11e7-9f2c-2d9861634245.png)

https://github.com/dcolley/DatePickerTest

**Comment by ParadeTo** [comment]
It is strange that your example works well on my computer.

![image](https://user-images.githubusercontent.com/10891388/31444553-21cdae36-ae62-11e7-9a69-e377334e45f4.png)

**Comment by dcolley** [comment]
How do you mean "works well"? Can you select another date range, like 18-19. And then leave the page. Then come back to the date range selector...?

**Comment by ParadeTo** [comment]
The reason why you only see the current date selected is that the startDate equals the endDate.

**Comment by dcolley** [comment]
So, my question relates to when the startDate and endDate do not cover today's date, e.g. in the screenshot I added - then why is today's date highlighted?
