### ISSUE TITLE
Move classes to parent for better styling.

### ISSUE THREAD

**Issue by Ethanhackett** [ParadeTo/vue-date-range#14]
The active classes should be moved to the parent `.ayou-day-cell` so that users can style things like `.in-range:first-of-type` etc. It would allow for more flexible styling options.

My goal would be to style the first and last days in unique ways then the days in between in different ways. to create a rounded row.

<img width="1001" alt="example" src="https://user-images.githubusercontent.com/480564/32058347-be3f3420-ba37-11e7-9404-539c83f1905e.png">

Another option that might be less obtrusive would be to add .start-date and .end-date classes.

**Comment by ParadeTo** [comment]
Can you pull a request?

**Comment by Ethanhackett** [comment]
@ParadeTo I created a pull request https://github.com/ParadeTo/vue-date-range/pull/15

You also might want to pick a .today styling. I just picked underline for the active day but you might find a more suitable styling that's more pronounced.

**Comment by ParadeTo** [comment]
Sorry, I think your way is not reasonable. So I commit some changes. Now you can set your style like this:

```
       .ayou-day-cell.start-day {
          border-bottom-left-radius: 50%;
          border-top-left-radius: 50%;
          background-color: transparent;
        }
        .ayou-day-cell.end-day {
          border-bottom-right-radius: 50%;
          border-top-right-radius: 50%;
          background-color: transparent;
        }
        .ayou-day-cell.in-range {
            background-color: orange;
        }
```

**Comment by Ethanhackett** [comment]
Yeah sorry I couldn't get your dev environment up to test what I wrote. But I pulled your latest commit and I do see the classes have been bumped up to the parent containers which will allow for more finer css control. Thanks for updating this!!! 🍻

**Comment by Ethanhackett** [comment]
<img width="385" alt="screen shot 2017-10-26 at 11 51 25 pm" src="https://user-images.githubusercontent.com/480564/32087268-9ea24e38-baa8-11e7-9aa5-d5109c280323.png">
