### ISSUE TITLE
Add a :day-week-format prop

### ISSUE THREAD

**Issue by nothingrandom** [ParadeTo/vue-date-range#29]
Allow for the top of the calendar to say M T W T F S S, or Mon Tues ..., or Monday Tuesday ...

**Comment by nothingrandom** [comment]
I'm currently using the following as a work around to get access to single letter days

```
.ayou-calendar .week-days span {
  font-size: 0 !important;
}

.ayou-calendar .week-days span::first-letter {
  font-size: 1rem;
}
```

**Comment by ParadeTo** [comment]
c7193cd58ed23b67a543785ad8b07757cdfc7554
