### ISSUE TITLE
"v-date-end-day" class is before "v-date-start-day" in DateRange

### ISSUE THREAD

**Issue by nirazul** [ParadeTo/vue-date-range#30]
First of all, thank you for this nice component. It works really well out of the box!

I've found a weird behaviour and I'm not sure if it's wanted or not: 

When I select one date and then the other one (which is before the startDate), the class for the `startDate` is on the later date and the class for the `endDate` is on the earlier date.

**Example:**
- I click on 31. July 2018
- I click on 1. July 2018

`.v-date-start-day` is on 31. July
`.v-date-end-day` is on 1. July

Is there a way to always have a class on the earlier date and one on the later date?

**Comment by nirazul** [comment]
Ok, I'm not able to reproduce it now... Maybe it has something to do with hooking it to a model... I'll investigate and reopen if I see it again...

**Comment by ParadeTo** [comment]
😆

**Comment by ParadeTo** [comment]
can you help to fix it?
