### ISSUE TITLE
v-date-selected on wrong cell

### ISSUE THREAD

**Issue by jamiechong** [ParadeTo/vue-date-range#31]
If I select a range of dates, then programmatically change my daterange object, the startDate cell of the range I selected keeps its v-date-selected class, but shouldn't. 

To reproduce: 

1. click date cell August  19, 2018 to select the startDate
2. click date cell August 24, 2018 to select the endDate
3. programmatically set `this.daterange.startDate = this.daterange.endDate = moment('2018-08-03');`

You will see the cell for August 19, 2018 still has `v-date-selected`. 

![vue-date-range-bug](https://user-images.githubusercontent.com/981664/43668287-f336b21c-9730-11e8-9fb0-26acd3fb58db.gif)

**Comment by ParadeTo** [comment]
please set `daterange ` like this:

```
        this.range = {
          startDate: moment('2018-08-03'),
          endDate: moment('2018-08-03')
        }
```

**Comment by jamiechong** [comment]
Good workaround. Thanks.
