### ISSUE TITLE
Calendar should handle no initial date

### ISSUE THREAD

**Issue by nirazul** [ParadeTo/vue-date-range#33]
I'm using the calendar together with two input fields for a start and end date, which are synced whenever one of the fields or the calendar is updated.

At the beginning, no date is inserted. This is no problem for the input fields, but the calendar will break when no Moment date is inserted.

Could you change the behaviour to allow for an initial value of `null`?

**Comment by nirazul** [comment]
Hey there, yes of course. [Here you go!](https://codepen.io/nirazul/pen/GXJJKY)

**Comment by ParadeTo** [comment]
fix 3ea3e9c3ef9a6268fb2c5ff0c31793215a75f7dd

**Comment by nirazul** [comment]
Awesome, thanks!
