### ISSUE TITLE
Disable mouse hover text from days (lunarText)

### ISSUE THREAD

**Issue by Dgaspar3** [ParadeTo/vue-date-range#5]
It would be great if we could disable :title="lunarText" when hovering the day.
Other good option would be changing the hover text to the selected language.

Thank you

**Comment by ParadeTo** [comment]
![image](https://user-images.githubusercontent.com/10891388/27680230-a20ffda4-5ced-11e7-8545-c078684e7783.png)

**Comment by Dgaspar3** [comment]
Yes
