### ISSUE TITLE
 Couldn't find preset "es2015" ?

### ISSUE THREAD

**Issue by huyansheng3** [ParadeTo/vue-date-range#6]
Error: Couldn't find preset "es2015" relative to directory "/Users/MacBook/Documents/2017/fiiish-m/node_modules/vue-date-range"

when i remove the "presets": ["es2015", "stage-2"], it wiil be ok. 
so why add the babelrc to the direction?

**Comment by ParadeTo** [comment]
c549a5c9f0b7937f
