### ISSUE TITLE
Disable multiple breaks between dates

### ISSUE THREAD

**Issue by Dgaspar3** [ParadeTo/vue-date-range#7]
Currently (from what I know) `days-disabled-start:` and `days-disabled-end:` only allow disabling one date break (example: disable all dates between 04/07/2017 and 22/07/2017).

It would be better if instead of a single break, we could disable multiple ones.

Example: 
Disable Dates:
**Start:** 04/07/2017; **End:** 22/07/2017
**Start:** 08/08/2017; **End:** 10/08/2017

Thanks in advance.

**Comment by ParadeTo** [comment]
you can use disabled-func

**Comment by Dgaspar3** [comment]
Ok, thats exactly what I need... but it still causes a problem.
 
All my data is dynamic, so I need to call the disableFunc everytime the values are changed.
Is there a way to trigger the function?

**Comment by ParadeTo** [comment]
I think you can watch your data, and redefine disableFunc in it:

```
watch: {
          range: function (val) {
            this.disabledFunc = function (dayMoment) {
              if (dayMoment.diff(val.s1) >= 0 && dayMoment.diff(val.e1) <= 0) {
                return true
              }
              return false
            }
          }
        },
```
