### ISSUE TITLE
Please add v-model support.

### ISSUE THREAD

**Issue by 634750802** [ParadeTo/vue-date-range#8]
[Form Input Components using Custom Events](https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events)

**Comment by ParadeTo** [comment]
I think this is what you want: https://vuejs.org/v2/guide/components.html#sync-Modifier

**Comment by ParadeTo** [comment]
1885dc27d5ce66eed8afd70afcca7f5236374937

**Comment by 634750802** [comment]
然而感觉上`v-model`更加直观，也能让组件用起来更像一个form input。

**Comment by ParadeTo** [comment]
那个是用在input标签上的，对本组件不适用

**Comment by ParadeTo** [comment]
恩，有空看看，现在这种方式也达到了“双向绑定”的效果

**Comment by ParadeTo** [comment]
@634750802 这种方式应该只适合用在input标签上

**Comment by ParadeTo** [comment]
4cfe0c0ac98cc68895070b7847e6da4c082b53f0

**Comment by 634750802** [comment]
对于一个📅组件，感觉大部分时间还是用作表单，所以感觉和input统一一下更合适吧。

**Comment by ParadeTo** [comment]
你可以封装成你自己的组件，就像Live Demo中的一样
